server:
  port: 8888


spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://192.168.161.3:3306/testdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: test
    password: 4rfv$RFV
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/

debug: true

logging:
    level:
      com.zimug.bootlaunch: debug

mybatis:
    configuration:
      mapUnderscoreToCamelCase: true